# Generated by Django 4.2.5 on 2024-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscillo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecolors',
            name='Math_signal_D',
        ),
        migrations.RemoveField(
            model_name='favoritecolors',
            name='Math_signal_L',
        ),
        migrations.AddField(
            model_name='favoritecolors',
            name='Theme_saved',
            field=models.CharField(default='dark', max_length=6),
        ),
    ]
